language: generic
sudo: required

services:
  - docker
env:
  # - API_URL=https://api-serverr.herokuapp.com/

before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

script:
  - docker build -t $DOCKER_USERNAME/$HEROKU_APP_NAME -f Dockerfile .
  - docker tag $DOCKER_USERNAME/$HEROKU_APP_NAME registry.heroku.com/$HEROKU_APP_NAME/worker

deploy:
  provider: script
  script:
    # push to dockerhub & heroku
    docker push $DOCKER_USERNAME/$HEROKU_APP_NAME;
    docker push registry.heroku.com/$HEROKU_APP_NAME/worker;
    heroku container:release worker --app $HEROKU_APP_NAME;
  on:
    branch: main