version: '3.7'

services:
  user-service:
    container_name: user-service
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./development.env
    networks:
      - my-network

networks:
  my-network:
    external: true
