export enum PayPalOnboardStatus {
  ONBOARD = 'ONBOARD',
  TRY_AGAIN = 'TRY_AGAIN',
  SELLER_CANNOT_RECEIVE_PAYMENT = 'SELLER_CANNOT_RECEIVE_PAYMENT',
  SELLER_EMAIL_WAS_NOT_CONFIRMED = 'SELLER_EMAIL_WAS_NOT_CONFIRMED',
  SELLER_DID_NOT_GRANT_PERMISSION = 'SELLER_DID_NOT_GRANT_PERMISSION',
}
