export const NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE';
export const DELIVERY_SERVICE = 'DELIVERY_SERVICE ';
export const USER_SERVICE = 'USER_SERVICE ';
export const ORDER_SERVICE = 'ORDER_SERVICE ';
export const RESTAURANT_SERVICE = 'RESTAURANT_SERVICE ';
